services:
  ro-browser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      # You can use to serve wsproxy.
      #- "5999:5999"
    volumes:
      - ./:/app
    tty: true
    command: ['sleep', '360h']

